services:
  db:
    image: postgres
    container_name: gestion_escolar_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestion_escolar_db
    env_file:
      - "dev.env"